### ISSUE TITLE
PyPI installation -- missing requirements?

### ISSUE THREAD

**Issue by vreuter** [databio/yacman#3]
```
master└─ $ pip install yacman
Collecting yacman
  Downloading https://files.pythonhosted.org/packages/b5/08/371ffd497c6f74d088a23d6b04b44a104adca2290b1c5ded651c70142795/yacman-0.1.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6tp4x3ko/yacman/setup.py", line 9, in <module>
        with open("requirements/requirements-all.txt", "r") as reqs_file:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements/requirements-all.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-6tp4x3ko/yacman/

```

**Comment by vreuter** [comment]
@nsheff is this a missing manifest case?

**Comment by nsheff** [comment]
yep.
