### ISSUE TITLE
Issue with file lock on cancelled jobs

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#51]
Not sure where this should go, but this has happened to me repeatedly now... if I cancel something (like with Ctrl +C), then I get an error like this:

```
Calling pre-submit function: refgenconf.looper_refgenie_plugin                                                                     
^CTraceback (most recent call last):                                                                                               
  File "/home/ns5bc/.local/bin/looper", line 8, in <module>                                                                        
    sys.exit(main())                                                                                                               
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/looper.py", line 987, in main                                        
    run(args, rerun=(args.command == "rerun"), **compute_kwargs)                                                                   
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/looper.py", line 443, in __call__                                    
    curr_pl_fails = cndtr.add_sample(sample, rerun=rerun)                                                                          
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/conductor.py", line 366, in add_sample                               
    self.submit()                                                                                                                  
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/conductor.py", line 403, in submit                                   
    script = self.write_script(self._pool, self._curr_size)                                                                        
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/conductor.py", line 591, in write_script                             
    namespaces = _exec_pre_submit(self.pl_iface, namespaces)                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/looper/conductor.py", line 696, in _exec_pre_submit                         
    _update_namespaces(namespaces, func(namespaces))                                                                               
  File "/home/ns5bc/.local/lib/python3.8/site-packages/refgenconf/populator.py", line 26, in looper_refgenie_plugin                
    rgc = refgenconf.RefGenConf(rgc_path)                                                                                          
  File "/home/ns5bc/.local/lib/python3.8/site-packages/refgenconf/refgenconf.py", line 103, in __init__                            
    super(RefGenConf, self).__init__(                                                                                              
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yacman/yacman.py", line 123, in __init__                                    
    file_contents = load_yaml(filepath)                                                                                            
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yacman/yacman.py", line 434, in load_yaml                                   
    return read_yaml_file(filepath)                                                                                                
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yacman/yacman.py", line 415, in read_yaml_file                              
    data = yaml.safe_load(f)                                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/__init__.py", line 162, in safe_load                                   
    return load(stream, SafeLoader)                                                                                                
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/__init__.py", line 114, in load                                        
    return loader.get_single_data()                                                                                                
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/constructor.py", line 49, in get_single_data                           
    node = self.get_single_node()                                                                                                  
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 36, in get_single_node                              
    document = self.compose_document()                                                                                             
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 55, in compose_document                             
    node = self.compose_node(None, None)                                                                                           
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 133, in compose_mapping_node                        
    item_value = self.compose_node(node, item_key)                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 84, in compose_node                                 
    node = self.compose_mapping_node(anchor)                                                                                       
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/composer.py", line 127, in compose_mapping_node                        
    while not self.check_event(MappingEndEvent):                                                                                   
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/parser.py", line 98, in check_event                                    
    self.current_event = self.state()                                                                                              
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/parser.py", line 432, in parse_block_mapping_key                       
    return self.parse_block_node_or_indentless_sequence()                                                                          
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/parser.py", line 271, in parse_block_node_or_indentless_sequence       
    return self.parse_node(block=True, indentless_sequence=True)                                                                   
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/parser.py", line 325, in parse_node                                    
    if self.check_token(ScalarToken):                                                                                              
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/scanner.py", line 115, in check_token                                  
    while self.need_more_tokens():                                                                                                 
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yaml/scanner.py", line 148, in need_more_tokens                             
    if not self.tokens:                                                                                                            
KeyboardInterrupt                                                                                                                  
Exception ignored in: <function YacAttMap.__del__ at 0x2b271246ba60>                                                               
Traceback (most recent call last):
  File "/home/ns5bc/.local/lib/python3.8/site-packages/yacman/yacman.py", line 157, in __del__
    if hasattr(self[IK], FILEPATH_KEY) and not getattr(self[IK], RO_KEY, True):
  File "/home/ns5bc/.local/lib/python3.8/site-packages/attmap/pathex_attmap.py", line 56, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/home/ns5bc/.local/lib/python3.8/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/home/ns5bc/.local/lib/python3.8/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: '__internal'
```

And then it locks the file erroenously, and the next time I try to do something I can't cause it's locked.
so we need some provision to auto-unlock probably using an `at_exit` function in these packages that lock stuff.

```
Waiting for file lock: /project/shefflab//deploy/btref.databio.org/btref.databio.org/config/lock.refgenie_config.yaml ..........^CT
raceback (most recent call last):

```

**Comment by stolarczyk** [comment]
How about registering an atexit function in the YacAttMap object constructor?

**Comment by nsheff** [comment]
yeah, something like that is what I was thinking
