### ISSUE TITLE
python 2 error

### ISSUE THREAD

**Issue by nsheff** [databio/yacman#6]
Related to Pathex attmap:

```
import yacman
>>> yacmap = yacman.YacAttMap("code/refgenconf/test.yaml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sheffien/.local/lib/python2.7/site-packages/yacman/yacman.py", line 19, in __init__
    self._file_path = entries
  File "/home/sheffien/.local/lib/python2.7/site-packages/attmap/ordattmap.py", line 27, in __setattr__
    self[name] = value
  File "/home/sheffien/.local/lib/python2.7/site-packages/attmap/ordattmap.py", line 44, in __setitem__
    super(OrdAttMap, self).__setitem__(key, self._final_for_store(value))
  File "/usr/lib/python2.7/collections.py", line 59, in __setitem__
    root = self.__root
  File "/home/sheffien/.local/lib/python2.7/site-packages/attmap/pathex_attmap.py", line 38, in __getattr__
    raise AttributeError(item)
AttributeError: _OrderedDict__root
```

@vreuter do you know off the top of your head what's going on here?

**Comment by vreuter** [comment]
Yeah an attribute is trying to be set before any superclass ctor call happens.
